#!/bin/bash
rm -f tmp/*;
#gazebo --verbose tank8-empty-field.world &
#gazebo --verbose simbot-2022-field.world &
gazebo --verbose simbot-2022-climber.world &
#gazebo --verbose simbot-empty-field.world &

